# Generated by Django 3.1.7 on 2021-03-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210309_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(db_column='DateTime', max_length=6)),
                ('jobNumber', models.IntegerField(db_column='JobNumber', max_length=11)),
                ('deviceName', models.CharField(db_column='DeviceName', max_length=64)),
                ('assetNumber', models.CharField(db_column='AssetNumber', max_length=64)),
                ('status', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'AIM_assetsrelatedstatement',
            },
        ),
    ]
