# Generated by Django 3.1.7 on 2021-03-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='jobNumber',
            field=models.IntegerField(db_column='JobNumber'),
        ),
    ]
